version: 0.0
os: windows
files:
  - source: \
    destination: C:\inetpub\wwwroot
    overwrite: yes
hooks:
  BeforeInstall:
    - location: scripts\stop_server.bat
      timeout: 300
      runas: Administrator
  AfterInstall:
    - location: scripts\install_dependencies.bat
      timeout: 600
      runas: Administrator
  ApplicationStart:
    - location: scripts\start_server.bat
      timeout: 300
      runas: Administrator